#!/usr/bin/env bash
set -Eeuo pipefail

trap 'echo "安装失败：第 ${LINENO} 行执行出错，请检查上方错误信息。" >&2' ERR

if [[ "$(uname -s)" != Linux ]]; then
  echo '此脚本仅支持 Linux。' >&2
  exit 1
fi

for cmd in curl gzip chmod mv mkdir getent awk grep pgrep pkill nohup ss; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "缺少命令：$cmd，请先安装后重新运行。" >&2
    exit 1
  fi
done

case "$(uname -m)" in
  x86_64) arch=amd64-compatible ;;
  aarch64|arm64) arch=arm64 ;;
  *) echo "暂不支持架构：$(uname -m)" >&2; exit 1 ;;
esac

sudo_cmd=()
if (( EUID != 0 )); then
  if ! command -v sudo >/dev/null 2>&1; then
    echo '请安装 sudo，或使用 root 用户运行。' >&2
    exit 1
  fi
  sudo -v
  sudo_cmd=(sudo)
fi

download() {
  local file="$1" url="$2"
  if [[ -f "$file" ]]; then
    echo "文件已存在，跳过下载：$file"
    return
  fi
  echo "正在下载：$file"
  # 下载成功后才使用正式文件名，避免下次误用未完成的下载。
  curl -fL --retry 3 --connect-timeout 15 --max-time 600 \
    "$url" -o "$file.part" || return $?
  mv -f "$file.part" "$file"
}

echo '正在查询官方 Releases 最新稳定版本……'
release_url="$(curl -fsSL --retry 3 --connect-timeout 15 --max-time 120 \
  -o /dev/null -w '%{url_effective}' \
  https://github.com/MetaCubeX/mihomo/releases/latest)"
version="${release_url##*/}"
if [[ ! "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "无法获取稳定版本号，返回地址：$release_url" >&2
  exit 1
fi

asset="mihomo-linux-${arch}-${version}.gz"
echo "最新稳定版本：$version"
download "$asset" "https://github.com/MetaCubeX/mihomo/releases/download/${version}/${asset}"

echo '正在解压并安装 mihomo……'
gzip -t "$asset"
gzip -dc "$asset" > mihomo
"${sudo_cmd[@]}" mkdir -p /usr/local/bin
"${sudo_cmd[@]}" mv -f mihomo /usr/local/bin/mihomo
"${sudo_cmd[@]}" chmod 755 /usr/local/bin/mihomo

echo '检查安装结果：'
if /usr/local/bin/mihomo -v; then
  echo 'Mihomo 安装成功。'
else
  echo 'Mihomo 安装失败：mihomo -v 执行失败。' >&2
  exit 1
fi

"${sudo_cmd[@]}" mkdir -p /etc/mihomo
for file in geoip.metadb geosite.dat; do
  if [[ ! -f "$file" && -f "/etc/mihomo/$file" ]]; then
    echo "文件已存在，跳过下载：/etc/mihomo/$file"
    [[ -s "/etc/mihomo/$file" ]] || { echo "文件为空，请删除后重试：/etc/mihomo/$file" >&2; exit 1; }
    continue
  fi
  download "$file" "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/$file"
  [[ -s "$file" ]] || { echo "文件为空，请删除后重试：$file" >&2; exit 1; }
  "${sudo_cmd[@]}" mv -f "$file" "/etc/mihomo/$file"
done
echo '安装完毕，数据文件已保存到 /etc/mihomo。'

echo '正在配置 alias……'
# sudo bash install.sh 时，将 alias 写入发起调用的用户目录。
alias_user="${SUDO_USER:-$(id -un)}"
user_entry="$(getent passwd "$alias_user")"
alias_home="$(printf '%s' "$user_entry" | awk -F: '{print $6}')"
alias_shell="$(printf '%s' "$user_entry" | awk -F: '{print $7}')"
case "$alias_shell" in
  */zsh) shell_rc="$alias_home/.zshrc" ;;
  *) shell_rc="$alias_home/.bashrc" ;;
esac
alias_file="$alias_home/.mihomo-aliases"

# root 可直接执行；普通用户通过 sudo 管理后台进程。
"${sudo_cmd[@]}" tee "$alias_file" >/dev/null <<'EOF'
# Generated by mihomo/install.sh
_mihomo_admin() {
  if [ "$(id -u)" = 0 ]; then "$@"; else sudo "$@"; fi
}
alias mihomo-start='_mihomo_admin sh -c '\''if pgrep -f "^/usr/local/bin/mihomo -d /etc/mihomo$" >/dev/null; then echo "Mihomo 已在运行"; else /usr/local/bin/mihomo -t -d /etc/mihomo || exit; umask 077; nohup /usr/local/bin/mihomo -d /etc/mihomo >> /etc/mihomo/mihomo.log 2>&1 < /dev/null & echo "Mihomo 已后台启动，请用 mihomo-log 查看运行结果"; fi'\'''
alias mihomo-stop='_mihomo_admin pkill -TERM -f "^/usr/local/bin/mihomo -d /etc/mihomo$"'
alias mihomo-log='_mihomo_admin tail -n 50 -f /etc/mihomo/mihomo.log'
alias mihomo-ports='_mihomo_admin ss -lntup | grep -E "mihomo|:(7890|9090)([[:space:]]|$)"'
EOF
"${sudo_cmd[@]}" chown "$alias_user" "$alias_file"
"${sudo_cmd[@]}" chmod 644 "$alias_file"

source_line='[ ! -f "$HOME/.mihomo-aliases" ] || . "$HOME/.mihomo-aliases"'
if ! grep -Fqx "$source_line" "$shell_rc" 2>/dev/null; then
  printf '\n%s\n' "$source_line" | "${sudo_cmd[@]}" tee -a "$shell_rc" >/dev/null
  "${sudo_cmd[@]}" chown "$alias_user" "$shell_rc"
fi
echo "Alias 已写入 $alias_file，重新执行安装不会重复追加。"
echo "请执行：source $shell_rc"
echo '可用命令：mihomo-start / mihomo-stop / mihomo-log / mihomo-ports'
